# Cross validation

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
from sklearn.datasets import load_digits

In [2]:
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [4]:
#Logistic regression
lr = LogisticRegression(solver = "newton-cg")
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9666666666666667

In [5]:
#Support vector machine
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [6]:
#Random forest
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9648148148148148

### K-fold

In [7]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3) #spicify how many folds you want to create
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [8]:
#use the kfold in the dataset
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


This returned an iterator and that iterator will return tarin and test index for each of the iterations. 
So it divided this [1,2,3,4,5,6,7,8,9] into 3 folds, and the first iteration uses one fold for testing [0 1 2] and the remaining two folds for training [3 4 5 6 7 8]. The second iteration it will move this fold to training [0 1 2] and this fold into testing [3 4 5 6 7 8]. and repeats the procedure.

In [9]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [10]:
#example how to use the function
get_score(LogisticRegression(solver = "newton-cg"), X_train,X_test,y_train,y_test)

0.9666666666666667

In [11]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [12]:
#explain how it works kfold
#scores array
scores_l = []
scores_svm = []
scores_rf = []

#it will give the score for each fold
for train_index, test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(solver = "newton-cg"), X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(), X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train,X_test,y_train,y_test))

In [13]:
scores_l

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [14]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [15]:
scores_rf

[0.9348914858096828, 0.9582637729549248, 0.9181969949916527]

In [16]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver = "newton-cg"), digits.data, digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [17]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [18]:
cross_val_score(RandomForestClassifier(), digits.data, digits.target)

array([0.92222222, 0.90277778, 0.94707521, 0.96100279, 0.93036212])

Exercise

Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

- Logistic Regression
- SVM
- Decision Tree
- Random Forest

In [19]:
from sklearn.datasets import load_iris
iris = load_iris()

In [20]:
l_scores = cross_val_score(LogisticRegression(solver = "newton-cg"), iris.data, iris.target)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [21]:
np.average(l_scores)

0.9733333333333334

In [22]:
svm_scores = cross_val_score(SVC(), iris.data, iris.target)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [23]:
np.average(svm_scores)

0.9666666666666666

In [24]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
rf_scores

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [25]:
np.average(rf_scores)

0.96

In [26]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [27]:
np.average(dt_scores)

0.9666666666666668